apiVersion: v2
name: osie
description: Deploy Osie into Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 23.9.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 23.9.6

dependencies:
  - name: mongodb
    version: 13.9.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 17.10.1
    condition: redis.enabled
  - name: rabbitmq
    version: 11.13.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled
  - name: keycloak
    version: 15.0.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak.enabled
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x